version: '3.9'

networks:
  balancer:
    ipam:
      driver: default
      config:
        - subnet: 172.129.0.16/28
services:

  haproxy:
    image: haproxy:2.7vlatest
    ports:
      - 443:443
      - 8080:8080
      - 8880:80
      - 8405:8405
    volumes:
#     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#      - /mnt/d/k8s/haproxy-lab/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/usr/local/etc/haproxy/certs
#      - /mnt/d/k8s/haproxy-lab/haproxy/certs/henderson:/usr/local/etc/haproxy/certs/henderson
      
    container_name: haproxy
    hostname: haproxy
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
     - balancer
